<!doctype html>  
<head>
    <base href="<?PHP echo $this->base; ?>" /> 

    <meta charset="utf-8">

    <title>selfoss</title>
	
    <meta name="description" content="selfoss">
    <meta name="author" content="Tobias Zeising">

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />
    
    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- all css definitions -->
    <link rel="stylesheet" href="all.css">

</head>
<body class="<?PHP if($this->publicMode===true) : ?>publicmode<?PHP endif; ?> <?PHP echo $this->loggedin ? "loggedin" : "notloggedin"; ?>">
	
	<!-- menue open for smartphone -->
	<div id="nav-showhide"></div>
	
    <!-- navigation -->
	<div id="nav">
		<div id="nav-logo"></div>
		<div id="nav-mark">mark as read</div>
		
		<ul id="nav-filter">
			<li class="nav-filter-newest active">newest <span><?PHP echo $this->statsAll; ?></span></li>
			<li class="nav-filter-unread">unread <span><?PHP echo $this->statsUnread; ?></span></li>
			<li class="nav-filter-starred">starred <span><?PHP echo $this->statsStarred; ?></span></li>
		</ul>
		
		<hr>
		
		<h2>Tags</h2>
		<div id="nav-tags-wrapper">
			<ul id="nav-tags">
				<li class="active nav-tags-all">all tags</li>
				<?PHP echo $this->tags; ?>
			</ul>
		</div>
		
		<hr>
		
		<!-- navigation search input just for smartphone version -->
		<div id="nav-search">
			<input type="text" id="nav-search-term"></input> <input type="button" id="nav-search-button" value="search" />
			<hr>
		</div>
		
		<div id="nav-settings"></div>
		<div id="nav-logout"></div>
	</div>
	
	<!-- search -->
	<div id="search">
		<input type="text" id="search-term"></input>
		<div id="search-remove"></div>
		<div id="search-button"></div>
		<div id="search-shownav"></div>
	</div>
	
	<ul id="search-list">
	</ul>
	
	<!-- content -->
	<div id="content">
		<?PHP echo $this->content; ?>
	</div>
	
	<!-- fullscreen popup -->
	<div id="fullscreen-entry"></div>
	
    <script src="all.js"></script>
</body>
</html>