<!doctype html>  
<head>
    <base href="<?PHP echo $this->base; ?>" /> 

    <meta charset="utf-8">

    <title>selfoss</title>
	
    <meta name="description" content="selfoss">
    <meta name="author" content="Tobias Zeising">

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />
    
    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- all css definitions -->
    <link rel="stylesheet" href="all.css">

</head>
<body class="<?PHP if($this->publicMode===true) : ?>publicmode<?PHP endif; ?> <?PHP echo $this->loggedin ? "loggedin" : "notloggedin"; ?>">

    <!-- navigation -->
	<div id="nav">
		<div id="nav-logo"></div>
		<div id="nav-mark">mark as read</div>
		
		<ul id="nav-filter">
			<li class="active">newest <span></span></li>
			<li>unread <span></span></li>
			<li>starred <span></span></li>
		</ul>
		
		<hr>
		
		<h2>Tags</h2>
		<ul id="nav-tags">
			<li>news <div class="color" style="background-color:#044476"></div></li>
			<li class="active">photography <div class="color" style="background-color:#004b18"></div></li>
			<li>downloads <div class="color" style="background-color:#e8641b"></div></li>
			<li>mobile <div class="color" style="background-color:#960014"></div></li>
			<li>ein sehr langer Tag der zu lang ist <div class="color" style="background-color:#e10052"></div></li>
		</ul>
		
		<hr>
		
		<div id="nav-settings"></div>
		<div id="nav-logout"></div>
	</div>
	
	
	<!-- content -->
	<div id="content">
		<?PHP echo $this->content; ?>
	</div>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<?PHP /*
	
	<a id="about" href="http://selfoss.aditu.de">selfoss <?PHP echo \F3::get('version'); ?></a>

    <!-- nav -->
    <nav class="columns on-3">
        <div class="container">
            <div id="nav-left"   class="column fixed" style="width:21px">&nbsp;</div>
            <div id="nav-middle" class="column elastic">
                <ul>
                    <?PHP if($this->loggedin===true && \F3::get('auth')->enabled()===true) : ?>
                    <li class="nav-logout">
                        <a href="<?PHP echo $this->base; ?>?logout=1"></a>
                    </li>
                    <?PHP endif; ?>
                    
                    <?PHP if($this->loggedin===true) : ?>
                    <li class="nav-settings">
                        <?PHP if(isset($this->sources) && $this->sources===true) : ?>
                        <a href="" class="active"></a>
                        <?PHP else : ?>
                        <a href="sources"></a>
                        <?PHP endif; ?>
                    </li>
                    
                    <?PHP else : ?>
                    <li class="nav-login">
                        <a href="<?PHP echo $this->base; ?>?login=1"></a>
                    </li>
                    <?PHP endif; ?>
                    
                    <li class="nav-favorites">
                        <?PHP if(isset($this->starred) && $this->starred===true) : ?>
                        <a href="<?PHP echo $this->base . (isset($this->search) ? '?search='.urlencode($this->search) : ''); ?>" class="active"></a>
                        <?PHP else : ?>
                        <a href="<?PHP echo $this->base; ?>?starred=1<?PHP echo isset($this->search) ? '&amp;search='.urlencode($this->search) : ''; ?>"></a>
                        <?PHP endif; ?>
                    </li>
                    
                    <li class="nav-search">
                        <form action="<?PHP echo $this->base; ?>" method="get">
                            <input type="text" id="search" name="search" value="<?PHP echo isset($this->search) ? $this->search : ''; ?>" />
                            <?PHP if(isset($this->starred) && $this->starred===true) : ?>
                            <input type="hidden" id="starred" value="1" name="starred" />
                            <?PHP endif; ?>
                            <div id="search-submit"></div>
                        </form>
                    </li>
                    <li class="nav-logo"></li>
                </ul>
            </div>
            <div id="nav-right"  class="column fixed" style="width:21px">&nbsp;</div>
        </div>
    </nav>
    
    <!-- stream -->
    <div id="wrapper">
        <div id="stream" class="columns on-3">
            <div class="container">
                <div id="stream-top-left"   class="stream-left column fixed" style="width:8px"></div>
                <div id="stream-top-middle" class="stream-middle column elastic"></div>
                <div id="stream-top-right"  class="stream-right column fixed" style="width:8px"></div>
                
                <div class="stream-left column fixed full-height" style="width:8px"></div>
                <div class="stream-middle stream-content column elastic">

                <?PHP echo $this->content; ?>
                
                </div>
                <div class="stream-right column fixed full-height" style="width:8px"></div>
            </div>
        </div>
    </div>*/ ?>

    <script src="all.js"></script>
    <script>selfoss.init();</script>
</body>
</html>