version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      client:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      composer:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
