<!doctype html>
<html>
<head>
    <meta charset="utf-8">

    <title>selfoss</title>

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1" />

    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=yes" media="(device-height: 568px)" />

    <!-- Web application behavior -->
    <meta name="application-name" content="selfoss" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <link rel="stylesheet" href="<?= \helpers\View::getGlobalCssFileName(); ?>" />

</head>
<body id="hashpashwordbody">

    <main>
        <form action="password" method="post">
        <ul id="login">
            <li><h1>hash generator</h1></li>
            <li><label for="password">Password:</label> <input type="password" name="password" id="password" autocomplete="new-password" accesskey="p"></li>
            <?php if (isset($this->hash)) : ?>
            <li class="error"><label aria-live="assertive">&nbsp;</label>Generated Password (insert this in config.ini): <input type="text" id="hash" value="<?= $this->hash; ?>" /></li>
            <?php endif; ?>
            <li><label>&nbsp;</label><input class="button" type="submit" value="generate password" accesskey="g" /></li>
        </ul>
        </form>
    </main>

</body>
</html>
