<!doctype html>
<html>
<head>
    <meta charset="utf-8">

    <title>selfoss</title>

    <meta name="referrer" content="no-referrer" />

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1" />

    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=yes" media="(device-height: 568px)" />

    <!-- Web application behavior -->
    <meta name="application-name" content="selfoss" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />

    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <link rel="stylesheet" href="<?= \helpers\View::getGlobalCssFileName(); ?>" />

    <!-- web application manifest -->
    <link rel="manifest" href="selfoss.webmanifest">
</head>
<body>

    <div id="message"></div>

    <!-- language settings for jQuery -->
    <span id="lang"
        data-mark="<?= \F3::get('lang_mark'); ?>"
        data-unmark="<?= \F3::get('lang_unmark'); ?>"
        data-star="<?= \F3::get('lang_star'); ?>"
        data-unstar="<?= \F3::get('lang_unstar'); ?>"
        data-source_warn="<?= \F3::get('lang_source_warn'); ?>"
        data-source_saved="<?= \F3::get('lang_source_saved'); ?>"
        data-source_edit="<?= \F3::get('lang_source_edit'); ?>"
        data-reload_list="<?= \F3::get('lang_reload_list'); ?>"
        data-sources_refreshed="<?= \F3::get('lang_sources_refreshed'); ?>"
        data-app_update="<?= \F3::get('lang_app_update'); ?>"
        data-app_reload="<?= \F3::get('lang_app_reload'); ?>"
        data-error_session_expired="<?= \F3::get('lang_error_session_expired'); ?>"
        data-error_add_source="<?= \F3::get('lang_error_add_source'); ?>"
        data-error_delete_source="<?= \F3::get('lang_error_delete_source'); ?>"
        data-error_load_tags="<?= \F3::get('lang_error_load_tags'); ?>"
        data-error_unknown_tag="<?= \F3::get('lang_error_unknown_tag'); ?>"
        data-error_unknown_source="<?= \F3::get('lang_error_unknown_source'); ?>"
        data-error_mark_items="<?= \F3::get('lang_error_mark_items'); ?>"
        data-error_mark_item="<?= \F3::get('lang_error_mark_item'); ?>"
        data-error_star_item="<?= \F3::get('lang_error_star_item'); ?>"
        data-error_logout="<?= \F3::get('lang_error_logout'); ?>"
        data-error_loading="<?= \F3::get('lang_error_loading'); ?>"
        data-error_loading_stats="<?= \F3::get('lang_error_loading_stats'); ?>"
        data-error_saving_color="<?= \F3::get('lang_error_saving_color'); ?>"
        data-error_refreshing_source="<?= \F3::get('lang_error_refreshing_source'); ?>"
        data-error_sync="<?= \F3::get('lang_error_sync'); ?>"
        data-error_offline_storage="<?= \F3::get('lang_error_offline_storage'); ?>"
        data-error_invalid_subsection="<?= \F3::get('lang_error_invalid_subsection'); ?>"
        data-error_configuration="<?= \F3::get('lang_error_configuration'); ?>"
        data-seconds="<?= \F3::get('lang_seconds'); ?>"
        data-minutes="<?= \F3::get('lang_minutes'); ?>"
        data-hours="<?= \F3::get('lang_hours'); ?>"
        data-login_username="<?= \F3::get('lang_login_username'); ?>"
        data-login_password="<?= \F3::get('lang_login_password'); ?>"
        data-login_offline="<?= \F3::get('lang_login_offline'); ?>"
        data-login="<?= \F3::get('lang_login'); ?>"
        data-settingsbutton="<?= \F3::get('lang_settingsbutton'); ?>"
        data-markread="<?= \F3::get('lang_markread'); ?>"
        data-filter="<?= \F3::get('lang_filter'); ?>"
        data-newest="<?= \F3::get('lang_newest'); ?>"
        data-offline_count="<?= \F3::get('lang_offline_count'); ?>"
        data-online_count="<?= \F3::get('lang_online_count'); ?>"
        data-unread="<?= \F3::get('lang_unread'); ?>"
        data-starred="<?= \F3::get('lang_starred'); ?>"
        data-tags="<?= \F3::get('lang_tags'); ?>"
        data-alltags="<?= \F3::get('lang_alltags'); ?>"
        data-sources="<?= \F3::get('lang_sources'); ?>"
        data-search_label="<?= \F3::get('lang_search_label'); ?>"
        data-searchbutton="<?= \F3::get('lang_searchbutton'); ?>"
        data-refreshbutton="<?= \F3::get('lang_refreshbutton'); ?>"
        data-logoutbutton="<?= \F3::get('lang_logoutbutton'); ?>"
        data-loginbutton="<?= \F3::get('lang_loginbutton'); ?>"
        data-searchremove="<?= \F3::get('lang_searchremove'); ?>"
        data-no_entries="<?= \F3::get('lang_no_entries'); ?>"
        data-more="<?= \F3::get('lang_more'); ?>"
        data-streamerror="<?= \F3::get('lang_streamerror'); ?>">
    </span>

    <script src="<?= \helpers\View::getGlobalJsFileName(); ?>"></script>
</body>
</html>
