<!doctype html>
<html lang="<?= \F3::get('language'); ?>">
<head>
    <base href="<?= $this->base; ?>" />

    <meta charset="utf-8">

    <title><?= trim(\F3::get('html_title')); ?></title>

    <meta name="description" content="<?= trim(\F3::get('html_title')); ?>" />
    <meta name="author" content="Tobias Zeising" />
    <meta name="version" content="<?= \F3::get('version'); ?>" />
    <meta name="referrer" content="no-referrer" />

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1" />

    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=yes" media="(device-height: 568px)" />

    <!-- Web application behavior -->
    <meta name="application-name" content="<?= trim(\F3::get('html_title')); ?>" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    <!-- app tile and notification when adding link to Windows 8 start screen -->
    <meta name="msapplication-TileColor" content="#3d6d69" />
    <meta name="msapplication-square70x70logo" content="<?= $this->base; ?>win8-70-icon.png" />
    <meta name="msapplication-square150x150logo" content="<?= $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-wide310x150logo" content="<?= $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-square310x310logo" content="<?= $this->base; ?>win8-310-icon.png" />
    <meta name="msapplication-notification" content="cycle=1; frequency=30; polling-uri=<?= $this->base; ?>win8notifs" />
    <meta name="msapplication-badge" content="frequency=30; polling-uri=<?= $this->base; ?>badge" />

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />

    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <link rel="stylesheet" href="<?= \helpers\View::getGlobalCssFileName(); ?>" />

    <!-- web application manifest -->
    <link rel="manifest" href="selfoss.webmanifest">
</head>
<body class="
    <?= $this->allowPublicUpdate === true ? 'publicupdate' : ''; ?>
    <?= $this->publicMode === true ? 'publicmode' : ''; ?>
    <?= $this->authEnabled === true ? 'authenabled' : 'loggedin'; ?>
    <?= \F3::get('auto_mark_as_read') == 1 ? 'auto_mark_as_read' : ''; ?>
">

    <div id="message"></div>

    <!-- language settings for jQuery -->
    <span id="lang"
        data-mark="<?= \F3::get('lang_mark'); ?>"
        data-unmark="<?= \F3::get('lang_unmark'); ?>"
        data-star="<?= \F3::get('lang_star'); ?>"
        data-unstar="<?= \F3::get('lang_unstar'); ?>"
        data-source_warn="<?= \F3::get('lang_source_warn'); ?>"
        data-source_saved="<?= \F3::get('lang_source_saved'); ?>"
        data-source_edit="<?= \F3::get('lang_source_edit'); ?>"
        data-reload_list="<?= \F3::get('lang_reload_list'); ?>"
        data-sources_refreshed="<?= \F3::get('lang_sources_refreshed'); ?>"
        data-app_update="<?= \F3::get('lang_app_update'); ?>"
        data-app_reload="<?= \F3::get('lang_app_reload'); ?>"
        data-error_session_expired="<?= \F3::get('lang_error_session_expired'); ?>"
        data-error_add_source="<?= \F3::get('lang_error_add_source'); ?>"
        data-error_delete_source="<?= \F3::get('lang_error_delete_source'); ?>"
        data-error_load_tags="<?= \F3::get('lang_error_load_tags'); ?>"
        data-error_unknown_tag="<?= \F3::get('lang_error_unknown_tag'); ?>"
        data-error_unknown_source="<?= \F3::get('lang_error_unknown_source'); ?>"
        data-error_mark_items="<?= \F3::get('lang_error_mark_items'); ?>"
        data-error_mark_item="<?= \F3::get('lang_error_mark_item'); ?>"
        data-error_star_item="<?= \F3::get('lang_error_star_item'); ?>"
        data-error_logout="<?= \F3::get('lang_error_logout'); ?>"
        data-error_loading="<?= \F3::get('lang_error_loading'); ?>"
        data-error_loading_stats="<?= \F3::get('lang_error_loading_stats'); ?>"
        data-error_saving_color="<?= \F3::get('lang_error_saving_color'); ?>"
        data-error_refreshing_source="<?= \F3::get('lang_error_refreshing_source'); ?>"
        data-error_sync="<?= \F3::get('lang_error_sync'); ?>"
        data-error_offline_storage="<?= \F3::get('lang_error_offline_storage'); ?>"
        data-error_invalid_subsection="<?= \F3::get('lang_error_invalid_subsection'); ?>"
        data-error_configuration="<?= \F3::get('lang_error_configuration'); ?>"
        data-seconds="<?= \F3::get('lang_seconds'); ?>"
        data-minutes="<?= \F3::get('lang_minutes'); ?>"
        data-hours="<?= \F3::get('lang_hours'); ?>"></span>

    <div id="loginform">
        <form action="<?= $this->base; ?>" method="post">
        <ul id="login">
            <li><h1><?= trim(\F3::get('html_title')); ?> login</h1></li>
            <li><label for="username"><?= trim(\F3::get('lang_login_username')); ?></label> <input type="text" name="username" id="username" accesskey="u" autocomplete="username" required></li>
            <li><label for="password"><?= trim(\F3::get('lang_login_password')); ?></label> <input type="password" name="password" id="password" accesskey="p" autocomplete="current-password"></li>
            <li><label for="enableoffline"><?= trim(\F3::get('lang_login_offline')); ?></label> <input type="checkbox" name="enableoffline" id="enableoffline" accesskey="o"></li>
            <li class="error" aria-live="assertive"></li>
            <li class="button"><label>&nbsp;</label><input type="submit" accesskey="l" value="<?= \F3::get('lang_login'); ?>" /></li>
        </ul>
        </form>
    </div>

    <div id="mainui">
        <!-- menu open for smartphone -->
        <div id="nav-mobile" role="navigation">
            <div id="nav-mobile-logo">
                <div id="nav-mobile-count" class="unread-count offlineable">
                    <span class="offline-count offlineable"></span>
                    <span class="count"></span>
                </div>
            </div>
            <button id="nav-mobile-settings" accesskey="t" aria-label="<?= trim(\F3::get('lang_settingsbutton')); ?>"></button>
        </div>

        <!-- navigation -->
        <div id="nav" role="navigation">
            <div id="nav-logo"></div>
            <button accesskey="a" id="nav-mark"><?= \F3::get('lang_markread')?></button>

            <div id="nav-filter-wrapper">
            <h2><button type="button" id="nav-filter-title" class="nav-filter-expanded" aria-expanded="true"><?= \F3::get('lang_filter') ?></button></h2>
            <ul id="nav-filter" aria-labeledby="nav-filter-title">
                <li>
                    <a id="nav-filter-newest" class="nav-filter-newest" href="#">
                        <?= \F3::get('lang_newest')?>
                        <span class="offline-count offlineable" title="<?= \F3::get('lang_offline_count')?>"></span>
                        <span class="count" title="<?= \F3::get('lang_online_count')?>"></span>
                    </a>
                </li>
                <li>
                    <a id="nav-filter-unread" class="nav-filter-unread" href="#">
                        <?= \F3::get('lang_unread')?>
                        <span class="unread-count offlineable">
                            <span class="offline-count offlineable" title="<?= \F3::get('lang_offline_count')?>"></span>
                            <span class="count" title="<?= \F3::get('lang_online_count')?>"></span>
                        </span>
                    </a>
                </li>
                <li>
                    <a id="nav-filter-starred" class="nav-filter-starred" href="#">
                        <?= \F3::get('lang_starred') ?>
                        <span class="offline-count offlineable" title="<?= \F3::get('lang_offline_count')?>"></span>
                        <span class="count" title="<?= \F3::get('lang_online_count')?>"></span>
                    </a>
                </li>
            </ul>
            </div>

            <hr>

            <div id="nav-tags-wrapper">
            <h2><button type="button" id="nav-tags-title" class="nav-tags-expanded" aria-expanded="true"><?= \F3::get('lang_tags') ?></button></h2>
            <ul id="nav-tags" aria-labeledby="nav-tags-title">
                <li><a class="active nav-tags-all" href="#"><?= \F3::get('lang_alltags')?></a></li>
            </ul>
            <h2><button type="button" id="nav-sources-title" class="nav-sources-collapsed" aria-expanded="false"><?= \F3::get('lang_sources') ?></button></h2>
            <ul id="nav-sources" aria-labeledby="nav-sources-title">
            </ul>
            </div>

            <hr>

            <!-- navigation search input just for smartphone version -->
            <div id="nav-search" class="offlineable" role="search">
                <input aria-label="<?= \F3::get('lang_search_label') ?>" type="search" id="nav-search-term" accesskey="s"> <input type="button" id="nav-search-button" value="<?= \F3::get('lang_searchbutton')?>" accesskey="e">
                <hr>
            </div>

            <div class="nav-toolbar">
                <button id="nav-refresh" title="<?= trim(\F3::get('lang_refreshbutton')); ?>" aria-label="<?= trim(\F3::get('lang_refreshbutton')); ?>" accesskey="r"></button>
                <button id="nav-settings" title="<?= trim(\F3::get('lang_settingsbutton')); ?>" aria-label="<?= trim(\F3::get('lang_settingsbutton')); ?>" accesskey="t"></button>
                <button id="nav-logout" title="<?= trim(\F3::get('lang_logoutbutton')); ?>" aria-label="<?= trim(\F3::get('lang_logoutbutton')); ?>" accesskey="l"></button>

                <?php if ($this->publicMode === true) : ?>
                <button id="nav-login" title="<?= trim(\F3::get('lang_loginbutton')); ?>" aria-label="<?= trim(\F3::get('lang_loginbutton')); ?>" accesskey="l"></button>
                <?php endif; ?>
            </div>
        </div>

        <!-- search -->
        <div id="search" role="search" class="offlineable">
            <input aria-label="<?= \F3::get('lang_search_label') ?>" type="search" id="search-term" accesskey="s">
            <button id="search-remove" title="<?= \F3::get('lang_searchremove')?>" accesskey="h" aria-label="<?= \F3::get('lang_searchremove')?>"><img src="images/remove.png" aria-hidden="true" alt=""></button>
            <button id="search-button" title="<?= \F3::get('lang_searchbutton')?>" aria-label="<?= \F3::get('lang_searchbutton')?>" accesskey="e"><img src="images/search.png" alt=""></button>
        </div>

        <ul id="search-list">
        </ul>

        <!-- content -->
        <div id="content" role="main">
        </div>

        <div id="stream-buttons">
            <p aria-live="assertive" class="stream-empty"><?= trim(\F3::get('lang_no_entries')); ?></p>
            <button class="stream-button stream-more" accesskey="m" aria-label="<?= trim(\F3::get('lang_more')); ?>"><span><?= trim(\F3::get('lang_more')); ?></span></button>
            <button class="stream-button mark-these-read" aria-label="<?= trim(\F3::get('lang_markread')); ?></span>"><span><?= trim(\F3::get('lang_markread')); ?></span></button>
            <button class="stream-button stream-error" aria-live="assertive" aria-label="<?= trim(\F3::get('lang_streamerror')); ?>"><?= trim(\F3::get('lang_streamerror')); ?></button>
        </div>
    </div>

    <script src="<?= \helpers\View::getGlobalJsFileName(); ?>"></script>
</body>
</html>
