<?php
    $title = $this->item['title'];
    $author = $this->item['author'];
    //$content = html_entity_decode($this->item['content']);
    $content = str_replace('&#34;', '"', $this->item['content']);
    $sourcetitle = $this->item['sourcetitle'];
    $this->viewHelper = new \helpers\ViewHelper();
    if (isset($this->search)) {
        $sourcetitle = $this->viewHelper->highlight($sourcetitle, $this->search);
        $title = $this->viewHelper->highlight($title, $this->search);
        $content = $this->viewHelper->highlight($content, $this->search);
    }

    if (\F3::get('camo_key') != '') {
        $content = $this->viewHelper->camoflauge($content);
    }

    $title = $this->viewHelper->lazyimg($title);
    $content = $this->viewHelper->lazyimg($content);
?>
<div data-entry-id="<?= $this->item['id']; ?>"
     data-entry-source="<?= $this->item['source']; ?>"
     data-entry-datetime="<?= $this->viewHelper->date_iso8601($this->item['datetime']); ?>"
     data-entry-url="<?= $this->item['link']; ?>"
     class="entry <?= $this->item['unread'] == 1 ? 'unread' : ''; ?>" role="article">

    <!-- icon -->
    <a href="<?= \helpers\Anonymizer::anonymize($this->item['link']); ?>" class="entry-icon" tabindex="-1" rel="noopener noreferrer" aria-hidden="true">
        <?php if (strlen(trim($this->item['icon'])) > 0 && $this->item['icon'] != '0') : ?>
        <img src="<?= 'favicons/' . $this->item['icon']; ?>" aria-hidden="true" alt="" >
        <?php endif; ?>
    </a>

    <!-- title -->
    <h3 class="entry-title"><span class="entry-title-link" aria-expanded="false" role="link" tabindex="0"><?= $title; ?></span></h3>

    <span class="entry-tags">
        <?php foreach ($this->item['tags'] as $tag => $color) : ?>
            <span class="entry-tags-tag" style="color:<?= $color['foreColor']; ?>;background-color:<?= $color['backColor']; ?>"><?= $tag; ?></span>
        <?php endforeach; ?>
    </span>

    <!-- source -->
    <span class="entry-source"><?= $sourcetitle ?></span>

    <span class="entry-separator">&bull;</span>

    <!-- author -->
    <?php if (!empty($author)) : ?>
    <span class="entry-author"><?= $author; ?></span>
    <span class="entry-separator">&bull;</span>
    <?php endif; ?>

    <!-- datetime -->
    <a href="<?= \helpers\Anonymizer::anonymize($this->item['link']); ?>" class="entry-datetime" target="_blank" rel="noopener noreferrer"></a>

    <!-- thumbnail -->
    <?php if (\F3::get('show_thumbnails') && isset($this->item['thumbnail']) && strlen(trim($this->item['thumbnail'])) > 0) : ?>
    <div class="entry-thumbnail">
        <a href="<?= \helpers\Anonymizer::anonymize($this->item['link']); ?>" target="_blank" rel="noopener noreferrer">
            <img src="<?= 'thumbnails/' . $this->item['thumbnail']; ?>" alt="<?= htmLawed(htmlspecialchars_decode($this->item['title']), ['deny_attribute' => '*', 'elements' => '-*']); ?>" />
        </a>
    </div>
    <?php endif; ?>

    <!-- content -->
    <div class="entry-content <?php if (strlen(strip_tags($content)) < 500) : ?>entry-content-nocolumns<?php endif; ?>">
        <?= $content; ?>

        <div class="entry-smartphone-share">
            <ul aria-label="<?= \F3::get('lang_article_actions')?>">
                <li><button accesskey="o" aria-haspopup="true" class="entry-newwindow"><i class="fas fa-external-link-alt"></i> <?= \F3::get('lang_open_window')?></button></li>
                <li><button accesskey="n" class="entry-next"><i class="fas fa-arrow-right"></i> <?= \F3::get('lang_next')?></button></li>
            </ul>
        </div>
    </div>

    <!-- toolbar -->
    <ul aria-label="<?= \F3::get('lang_article_actions')?>" class="entry-toolbar">
        <li><button accesskey="a" class="entry-starr <?= $this->item['starred'] == 1 ? 'active' : ''; ?>"><i class="fa<?= $this->item['starred'] == 1 ? 's' : 'r'; ?> fa-star"></i> <?= $this->item['starred'] == 1 ? \F3::get('lang_unstar') : \F3::get('lang_star'); ?></button></li>
        <li><button accesskey="u" class="entry-unread <?= $this->item['unread'] == 1 ? 'active' : ''; ?>"><i class="fa<?= $this->item['unread'] == 1 ? 's' : 'r'; ?> fa-check-circle"></i> <?= $this->item['unread'] == 1 ? \F3::get('lang_mark') : \F3::get('lang_unmark'); ?></button></li>
        <li><button accesskey="o" class="entry-newwindow" aria-haspopup="true"><i class="fas fa-external-link-alt"></i> <?= \F3::get('lang_open_window')?></button></li>
        <li><button class="entry-loadimages"><i class="fas fa-arrow-alt-circle-down"></i> <?= \F3::get('lang_load_img')?> </button></li>
        <li><button accesskey="n" class="entry-next"><i class="fas fa-arrow-right"></i> <?= \F3::get('lang_next')?></button></li>
        <li><button accesskey="c" class="entry-close"><i class="far fa-times-circle"></i> <?= \F3::get('lang_close_entry')?></button></li>
    </ul>
</div>
