<!doctype html>
<html>
    <head>
        <meta charset="utf-8">

        <title>selfoss</title>

        <!--  Mobile viewport optimized: j.mp/bplateviewport -->
        <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1">

        <!--  Add support for fullscreen Webapp on iPhone 5 -->
        <meta name="viewport" content="initial-scale=1, user-scalable=yes" media="(device-height: 568px)" />

        <!-- Web application behavior -->
        <meta name="application-name" content="selfoss" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />

        <!-- icons -->
        <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
        <link rel="icon" type="image/png" href="icon-32x32.png" />
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

        <!-- Toolbar color from Chrome for Android -->
        <meta name="theme-color" content="#191718" />

        <!-- all css definitions -->
        <link rel="stylesheet" href="<?= \helpers\View::getGlobalCssFileName(); ?>">
    </head>
    <body id="opmlbody">

        <main>
            <form method="post" enctype="multipart/form-data">
                <ul id="opml">
                <li><h1>Upload an OPML File</h1></li>
                <li>
                    <p>
                    Coming from a different RSS Reader? Export your subscriptions to an OPML file and upload it here. OPML export is usually
                    located somewhere in settings, consult the reader’s manual.
                    </p>
                </li>
                <?php
                    if (isset($this->msg)) {
                        echo '<li class="msg ' . $this->msgclass . '"><p>' . $this->msg . '</p><li>';
                    }
                ?>
                <li class="center"><label for="opml">Opml.xml:</label> <input type="file" accesskey="f" name="opml" id="opml"></li>
                <li class="button"><label>&nbsp;</label><input type="submit" value="Deliver my OPML!" accesskey="d"></li>
                </ul>
            </form>
        </main>

        <script src="<?= \helpers\View::getGlobalJsFileName(); ?>"></script>
        <script type="text/javascript">
            $('form').submit(function() {
                $('input[type=submit]').prop('disabled', true).val('Importing...');
            });
        </script>
    </body>
</html>
