FROM php:7.4-apache-buster

ARG gid
ARG uid

RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y libpng-dev nodejs gcc g++ make unzip \
    && docker-php-ext-install -j$(nproc) gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && a2enmod rewrite

RUN curl -o /tmp/composer-setup.php "https://getcomposer.org/installer"; \
    EXPECTED_SIGNATURE="$(curl https://composer.github.io/installer.sig)"; \
    ACTUAL_SIGNATURE="$(sha384sum /tmp/composer-setup.php | cut -d ' ' -f 1)"; \
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then \
        >&2 echo 'ERROR: Invalid installer signature'; \
        rm /tmp/composer-setup.php && exit 1; \
    fi \
    && php /tmp/composer-setup.php --install-dir=/bin --filename=composer \
    && groupadd --gid ${gid} node \
    && useradd --uid ${uid} --gid node --shell /bin/bash --create-home node

ENV APACHE_RUN_USER=node APACHE_RUN_GROUP=node

VOLUME /var/www/html/

CMD [ "/var/www/html/utils/docker/entrypoint.dev.sh" ]
