<!doctype html>  

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <base href="<?PHP echo $this->base; ?>" /> 

    <meta charset="utf-8">

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
       Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>selfoss</title>
    <meta name="description" content="selfoss">
    <meta name="author" content="Tobias Zeising">

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />
    
    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- elastics -->
    <link rel="stylesheet" href="css/elastic.css" type="text/css" media="all" charset="utf-8" />  
    <link rel="stylesheet" href="css/elastic.print.css" type="text/css" media="print" charset="utf-8" />  
    
    <!-- CSS : implied media="all" -->
    <link rel="stylesheet" href="css/style.css?v=2">

    <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
    <script src="js/modernizr-1.6.min.js"></script>
    
</head>
<body class="<?PHP if($this->publicMode===true) : ?>publicmode<?PHP endif; ?>
 <?PHP echo $this->loggedin ? "loggedin" : "notloggedin"; ?>">

    <a id="about" href="http://selfoss.aditu.de">selfoss <?PHP echo \F3::get('version'); ?></a>

    <!-- nav -->
    <nav class="columns on-3">
        <div class="container">
            <div id="nav-left"   class="column fixed" style="width:21px">&nbsp;</div>
            <div id="nav-middle" class="column elastic">
                <ul>
                    <?PHP if($this->loggedin===true && \F3::get('auth')->enabled()===true) : ?>
                    <li class="nav-logout">
                        <a href="<?PHP echo $this->base; ?>?logout=1"></a>
                    </li>
                    <?PHP endif; ?>
                    
                    <?PHP if($this->loggedin===true) : ?>
                    <li class="nav-settings">
                        <?PHP if(isset($this->sources) && $this->sources===true) : ?>
                        <a href="" class="active"></a>
                        <?PHP else : ?>
                        <a href="sources"></a>
                        <?PHP endif; ?>
                    </li>
                    
                    <?PHP else : ?>
                    <li class="nav-login">
                        <a href="<?PHP echo $this->base; ?>?login=1"></a>
                    </li>
                    <?PHP endif; ?>
                    
                    <li class="nav-favorites">
                        <?PHP if(isset($this->starred) && $this->starred===true) : ?>
                        <a href="<?PHP echo $this->base . (isset($this->search) ? '?search='.urlencode($this->search) : ''); ?>" class="active"></a>
                        <?PHP else : ?>
                        <a href="<?PHP echo $this->base; ?>?starred=1<?PHP echo isset($this->search) ? '&amp;search='.urlencode($this->search) : ''; ?>"></a>
                        <?PHP endif; ?>
                    </li>
                    
                    <li class="nav-search">
                        <form action="<?PHP echo $this->base; ?>" method="get">
                            <input type="text" id="search" name="search" value="<?PHP echo isset($this->search) ? $this->search : ''; ?>" />
                            <?PHP if(isset($this->starred) && $this->starred===true) : ?>
                            <input type="hidden" id="starred" value="1" name="starred" />
                            <?PHP endif; ?>
                            <div id="search-submit"></div>
                        </form>
                    </li>
                    <li class="nav-logo"></li>
                </ul>
            </div>
            <div id="nav-right"  class="column fixed" style="width:21px">&nbsp;</div>
        </div>
    </nav>
    
    <!-- stream -->
    <div id="wrapper">
        <div id="stream" class="columns on-3">
            <div class="container">
                <div id="stream-top-left"   class="stream-left column fixed" style="width:8px"></div>
                <div id="stream-top-middle" class="stream-middle column elastic"></div>
                <div id="stream-top-right"  class="stream-right column fixed" style="width:8px"></div>
                
                <div class="stream-left column fixed full-height" style="width:8px"></div>
                <div class="stream-middle stream-content column elastic">

                <?PHP echo $this->content; ?>
                
                </div>
                <div class="stream-right column fixed full-height" style="width:8px"></div>
            </div>
        </div>
    </div>

    <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="js/jquery-1.6.1.min.js"%3E%3C/script%3E'))</script>

    <!-- elastic framework -->
    <script src="js/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>

    <!-- iscroll -->
    <script src="js/iscroll.js" type="text/javascript" language="javascript" charset="utf-8"></script>

    <!-- shortcuts -->
    <script src="js/shortcut-2.01.B.js" type="text/javascript" language="javascript" charset="utf-8"></script>
    
    <!-- rsslounge javascript -->
    <script src="js/base.js"></script>
    <script>selfoss.init();</script>
</body>
</html>