<?PHP
    $title = $this->item['title'];
    //$content = html_entity_decode($this->item['content']);
    $content = str_replace('&#34;', '"', $this->item['content']);
    $sourcetitle = $this->item['sourcetitle'];
    $this->viewHelper = new \helpers\ViewHelper();
    if(isset($this->search)) {
        $sourcetitle = $this->viewHelper->highlight($sourcetitle, $this->search);
        $title = $this->viewHelper->highlight($title, $this->search);
        $content = $this->viewHelper->highlight($content, $this->search);
    }
    $title = $this->viewHelper->lazyimg($title);
    $content = $this->viewHelper->lazyimg($content);
    $date = $this->viewHelper->dateago($this->item['datetime']);
?>
<div id="entry<?PHP echo $this->item['id']; ?>"
     class="entry
            <?PHP echo $this->item['unread']==1 ? 'unread' : ''; ?>">
    
    <!-- icon -->
    <a href="<?PHP echo $this->item['link']; ?>" class="entry-icon">
        <?PHP if(strlen(trim($this->item['icon']))>0 && $this->item['icon']!="0") : ?>
        <img src="<?PHP echo 'favicons/'.$this->item['icon']; ?>" alt="<?PHP echo $sourcetitle ?>" />
        <?PHP endif; ?>
    </a>
    
    <!-- title -->
    <h2 class="entry-title"><?PHP echo $title; ?></h2>
    
    <div class="entry-tags">
        <?PHP foreach($this->item['tags'] as $tag => $color) : ?>
            <div class="entry-tags-tag" style="background-color:<?PHP echo $color; ?>"><?PHP echo $tag; ?></div>
        <?PHP endforeach; ?>
    </div>
    
    <!-- source -->
    <a href="<?PHP echo $this->item['link']; ?>" class="entry-source entry-source<?PHP echo $this->item['source']; ?>" target="_blank"><?PHP echo $sourcetitle ?></a>
    
    <!-- datetime -->
    <div class="entry-datetime">
        &bullet; <?PHP echo $date; ?>
    </div>
    
    <!-- thumbnail -->
    <?PHP if(isset($this->item['thumbnail']) && strlen(trim($this->item['thumbnail']))>0) : ?>
    <div class="entry-thumbnail">
        <a href="<?PHP echo $this->item['link']; ?>"><img src="<?PHP echo 'thumbnails/'.$this->item['thumbnail']; ?>" alt="<?PHP echo $this->item['title']; ?>" /></a>
    </div>
    <?PHP endif; ?>
    
    <!-- content -->
    <div class="entry-content <?PHP if(strlen(strip_tags($content))<500) : ?>entry-content-short<?PHP endif; ?>">
        <?PHP echo $content; ?>
        
        <ul class="entry-smartphone-share">
			<?php if(\F3::get('sharegoogle')!="" || \F3::get('sharegoogle')!="Hide") : ?>
				<li title="google" class="entry-sharegoogle"><?php echo \F3::get('sharegoogle')=="ImageText" ? 'google': '&nbsp;'; ?></li>
			<?php endif; ?>
			
			<?php if(\F3::get('sharetwitter')!="" || \F3::get('sharetwitter')!="Hide") : ?>
				<li title="twitter" class="entry-sharetwitter"><?php echo \F3::get('sharetwitter')=="ImageText" ? 'twitter': '&nbsp;'; ?></li>
			<?php endif; ?>
			
			<?php if(\F3::get('sharefacebook')!="" || \F3::get('sharefacebook')!="Hide") : ?>
				<li title="facebook" class="entry-sharefacebook"><?php echo \F3::get('sharefacebook')=="ImageText" ? 'facebook': '&nbsp;'; ?></li>
			<?php endif; ?>
			
			<?php if(\F3::get('sharepocket')!="" || \F3::get('sharepocket')!="Hide") : ?>
				<li title="pocket" class="entry-sharepocket"><?php echo \F3::get('sharepocket')=="ImageText" ? 'pocket': '&nbsp;'; ?></li>
			<?php endif; ?>
			
			<?php if(\F3::get('shareemail')!="" || \F3::get('shareemail')!="Hide") : ?>
				<li title="email" class="entry-shareemail"><?php echo \F3::get('shareemail')=="ImageText" ? 'email': '&nbsp;'; ?></li>
			<?php endif; ?>
        </ul>
    </div>
    
    <!-- toolbar -->
    <ul class="entry-toolbar">
		<?php if(\F3::get('star')!="" || \F3::get('star')!="Hide") : ?>
			<li title="star/unstar" class="entry-starr <?PHP echo $this->item['starred']==1 ? 'active' : ''; ?>">
				<?php if(\F3::get('star')=="ImageText"): ?>
					<?PHP echo $this->item['starred']==1 ? 'unstar' : 'star'; ?>
				<?php else : ?>
					&nbsp;
				<?php endif; ?>
			</li>
		<?php endif; ?>
		
		<?php if(\F3::get('unread')!="" || \F3::get('unread')!="Hide") : ?>
			<li title="read/unread" class="entry-unread <?PHP echo $this->item['unread']==1 ? 'active' : ''; ?>">
				<?php if(\F3::get('unread')=="ImageText"): ?>
					<?PHP echo $this->item['unread']==1 ? 'mark as read' : 'mark as unread'; ?>
				<?php else : ?>
					&nbsp;
				<?php endif; ?>
			</li>
		<?php endif; ?>
		
       <?php if(\F3::get('open')!="" || \F3::get('open')!="Hide") : ?>
			<li class="entry-newwindow" title="open"><?php echo \F3::get('open')=="ImageText" ? 'open' : '&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('loadimages')!="" || \F3::get('loadimages')!="Hide") : ?>
			<li class="entry-loadimages" title="load images"><?php echo \F3::get('loadimages')=="ImageText" ? 'load images' : '&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('sharegoogle')!="" || \F3::get('sharegoogle')!="Hide") : ?>
			<li class="entry-sharegoogle entry-share" title="google"><?php echo \F3::get('sharegoogle')=="ImageText" ? 'google':'&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('sharetwitter')!="" || \F3::get('sharetwitter')!="Hide") : ?>
			<li class="entry-sharetwitter entry-share" title="twitter"><?php echo \F3::get('sharetwitter')=="ImageText" ? 'twitter':'&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('sharefacebook')!="" || \F3::get('sharefacebook')!="Hide") : ?>
			<li class="entry-sharefacebook entry-share" title="facebook"><?php echo \F3::get('sharefacebook')=="ImageText" ? 'facebook':'&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('sharepocket')!="" || \F3::get('sharepocket')!="Hide") : ?>
			<li class="entry-sharepocket entry-share" title="pocket"><?php echo \F3::get('sharepocket')=="ImageText" ? 'pocket':'&nbsp;'; ?></li>
		<?php endif; ?>
		
		<?php if(\F3::get('shareemail')!="" || \F3::get('shareemail')!="Hide") : ?>
			<li class="entry-shareemail entry-share" title="email"><?php echo \F3::get('shareemail')=="ImageText" ? 'email':'&nbsp;'; ?></li>
		<?php endif; ?>
        <li class="entry-close"></li>
    </ul>
</div>
