<!doctype html>
    <head>
        <base href="<?PHP echo $this->base; ?>" />

        <meta charset="utf-8">

        <title>selfoss</title>

        <meta name="description" content="selfoss">
        <meta name="author" content="Tobias Zeising">

        <!--  Mobile viewport optimized: j.mp/bplateviewport -->
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">

        <!--  Add support for fullscreen Webapp on iPhone 5 -->
        <meta name="viewport" content="initial-scale=1, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" />

        <link rel="shortcut icon" href="favicon.ico" />
        <link rel="apple-touch-icon" href="apple-touch-icon.png" />

        <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">
        <link rel="icon" type="image/png" href="favicon-196x196.png" sizes="196x196">
        <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="msapplication-TileImage" content="mstile-144x144.png">

        <!-- all css definitions -->
        <link rel="stylesheet" href="all.css">
    </head>
    <body id="opmlbody">
        <form method="post" enctype="multipart/form-data">
            <ul id="opml">
            <li><h1>Upload an OPML File</h1></li>
            <li>
                <p>
                Coming from Google Reader? Use <a href='http://www.google.com/reader/subscriptions/export'>Google Reader export</a> to get
                your Google Reader subscriptions into a .xml file.
                </p>
            </li>
            <?php
                if(isset($this->msg))
                echo '<li class="msg '.$this->msgclass.'"><p>'.$this->msg.'</p><li>';
            ?>
            <li class="center"><label>Opml.xml:</label> <input type="file" name="opml" /></li>
            <li class="button"><label>&nbsp;</label><input type="submit" value="Deliver my OPML!" /></li>
            </ul>
        </form>
        <script src="all.js"></script>
        <script type="text/javascript">
            $('form').submit(function() {
                $('input[type=submit]').prop('disabled', true).val('Importing...');
            });
        </script>
    </body>
</html>
