<!doctype html>  
    <head>
        <base href="<?PHP echo $this->base; ?>" /> 

        <meta charset="utf-8">

        <title><?PHP echo trim(\F3::get('html_title')); ?></title>
        
        <meta name="description" content="selfoss">
        <meta name="author" content="Tobias Zeising">

        <!--  Mobile viewport optimized: j.mp/bplateviewport -->
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
        
        <!--  Add support for fullscreen Webapp on iPhone 5 -->
        <meta name="viewport" content="initial-scale=1, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" />

        <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
        <link rel="shortcut icon" href="favicon.ico">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <!-- all css definitions -->
        <link rel="stylesheet" href="<?PHP echo \helpers\View::getGlobalCssFileName(); ?>">
    </head>
    <body id="opmlbody">
        <form method="post" enctype="multipart/form-data">
            <ul id="opml">
            <li><h1>Upload an OPML File</h1></li>
            <li>
                <p>
                Coming from Google Reader? Use <a href='http://www.google.com/reader/subscriptions/export'>Google Reader export</a> to get
                your Google Reader subscriptions into a .xml file.
                </p>
            </li>
            <?php
                if(isset($this->msg))
                echo '<li class="msg '.$this->msgclass.'"><p>'.$this->msg.'</p><li>';
            ?>
            <li class="center"><label>Opml.xml:</label> <input type="file" name="opml" /></li>
            <li class="button"><label>&nbsp;</label><input type="submit" value="Deliver my OPML!" /></li>
            </ul>
        </form>
        <script src="<?PHP echo \helpers\View::getGlobalJsFileName(); ?>"></script>
        <script type="text/javascript">
            $('form').submit(function() {
                $('input[type=submit]').prop('disabled', true).val('Importing...');
            });
        </script>
    </body>
</html>
