<tile>
  <visual lang="en-US" version="3" branding="logo">
      <binding template="TileSquare150x150PeekImageAndText02">
        <image id="1" src="<?php echo $this->base; ?>win8-150-icon.png" alt="Selfoss" />
        <text id="2">Selfoss</text>
      </binding>

      <binding template="TileSquare71x71IconWithBadge">
        <image id="1" src="<?php echo $this->base; ?>win8-71-icon.png" alt="Selfoss" />
      </binding>

      <binding template="TileSquare150x150IconWithBadge">
        <image id="1" src="<?php echo $this->base; ?>win8-150-icon.png" alt="Selfoss" />
      </binding>
  </visual>
</tile>
