<?php

/**
 * Default error page.
 *
 * @param bool $logged
 */

namespace Tracy;

?>
<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Tracy">
<title>selfoss failed</title>

<style>
    #tracy-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 80vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
    #tracy-error div { all: initial; max-width: 650px; background: white; color: #333; display: block }
    #tracy-error h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
    #tracy-error p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
    #tracy-error small { color: gray }
    #tracy-error small span { color: silver }
    #tracy-error code { background: #ddd; color: #222; padding: 0.1em 0.3em; border-radius: 0.2em; }
</style>

<div id=tracy-error>
    <div>
        <h1>selfoss failed</h1>

        <p>We’re sorry! selfoss encountered an unexpected error and was unable to complete your request.</p>

        <p>Please contact your administrator or try again later.</p>

        <p>If you are the administrator,
            <?php if ($logged) { ?>
                please check the logs or add
            <?php } else { ?>
                selfoss is unable to log the error, make sure the <code>data/logs</code> directory is writeable (if applicable), or try adding
            <?php } ?>
            <code>debug=1</code> to your selfoss instance configuration.</p>

        <p><small>error 500 <span> | <?= @date('j. n. Y H:i') ?></span></small></p>
    </div>
</div>

<script>
    document.body.insertBefore(document.getElementById('tracy-error'), document.body.firstChild);
</script>
