<?php

// SPDX-FileCopyrightText: 2021 David Grudl <david@grudl.com>
// SPDX-FileCopyrightText: 2023 Jan Tojnar <jtojnar@gmail.com>
// SPDX-License-Identifier: GPL-3.0-or-later

declare(strict_types=1);

use Tracy\Helpers;

/*
 * Default error page.
 *
 * @param bool $logged
 */

?>
<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Tracy">
<title>selfoss failed</title>

<style>
    #tracy-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000; font: 16px/1.4 sans-serif; color: #333 }
    #tracy-error * { all: initial; background: transparent; color: inherit; font: inherit }
    #tracy-error div { max-width: 550px; background: white; display: block }
    #tracy-error h1 { font: bold 50px/1.1 sans-serif; margin: 40px; display: block }
    #tracy-error p { font: 20px/1.4 sans-serif; margin: 40px; display: block }
    #tracy-error small { color: gray; font-size: 80% }
    #tracy-error small span { color: silver }
    #tracy-error code { background: #ddd; color: #222; padding: 0.1em 0.3em; border-radius: 0.2em; }
</style>

<div id=tracy-error>
    <div>
        <h1>selfoss failed</h1>

        <p>We’re sorry! selfoss encountered an unexpected error and was unable to complete your request.</p>

        <p>Please contact your administrator or try again later.</p>

        <p>If you are the administrator,
            <?php if ($logged) { ?>
                please check the logs or add
            <?php } else { ?>
                selfoss is unable to log the error, make sure the <code>data/logs</code> directory is writeable (if applicable), or try adding
            <?php } ?>
            <code>debug=1</code> to your selfoss instance configuration to get more information.</p>

        <p><small>error 500 <span> | <?= date('j. n. Y H:i') ?></span></small></p>
    </div>
</div>

<script<?= Helpers::getNonceAttr() ?>>
    document.body.insertBefore(document.getElementById('tracy-error'), document.body.firstChild);
</script>
